---
mysql_packages:
  - python-selinux
  - mysql-server
  - python-mysqldb
  - python3-pymysql
  - python-pymysql

mysql_service: mysql

mysql_conf_dir: /etc/mysql

mysql_port: 3306
mysql_bind_address: "0.0.0.0" #de esta manera podemos acceder desde ambos webservers"
#tambien podriamos hacerlo -> mysql_bind_address: "192.168.11.12, 192.168.33.13

mysql_root_db_pass: root

mysql_db:
  - name: "{{ db_name }}"

mysql_users:
  - name: "{{ db_user }}"
    pass: "{{ db_pass }}"
    priv: "*.*:ALL" #los privilegios se los damos todos no es lo mejor pero para este caso nos sirve

