---
- hosts: all
  remote_user: root
  tasks:
    - include: apache-tasks.yaml
  handlers:
    - include: apache-handlers.yaml


---
- include: apache-instalacion.yaml
- include: apache-configuracion.yaml


